# -*- coding: utf-8 -*-
"""bikes_regression.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1AlMdH5YQURYU3M763_epITyV1LBa20C_
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from imblearn.over_sampling import RandomOverSampler
from sklearn.preprocessing import StandardScaler
import copy
import seaborn as sns
import tensorflow as tf
from sklearn.linear_model import LinearRegression

dataset_cols = ['bike_count', 'hour', 'temp', 'humidity', 'wind', 'visibility', 'dew_pt_temp', 'radiation', 'rain', 'snow', 'functional']

df = pd.read_csv('SeoulBikeData.csv', encoding='latin1').drop(['Date', 'Holiday', 'Seasons'], axis=1)

df.head()

df.columns = dataset_cols
df['functional'] = (df['functional'] == 'Yes').astype(int)
df = df[df['hour'] == 12]
df = df.drop(['hour'], axis = 1)

df.head()

for label in df.columns[1:]:
  plt.scatter(df[label], df['bike_count'])
  plt.title(label)
  plt.ylabel('Bike Count at Noon')
  plt.xlabel(label)
  plt.show()

df = df.drop(['wind', 'visibility', 'functional'], axis = 1)

df.head()

"""##Train | Validation | Test Datasets"""

train, val, test = np.split(df.sample(frac=1), [int(0.6*len(df)), int(0.8*len(df))])

def get_xy(dataframe, y_label, x_labels=None):
  dataframe = copy.deepcopy(dataframe)
  if x_labels is None:
    X = dataframe[[c for c in dataframe.columns if c != y_label]].values
  else:
    if len(x_labels) == 1:
      X = dataframe[x_labels[0]].values.reshape(-1, 1)
    else:
      X = dataframe[x_labels].values
  y = dataframe[y_label].values.reshape(-1, 1)
  data = np.hstack((X, y))
  return data, X, y

_, X_train_temp, y_train_temp = get_xy(train, 'bike_count', ['temp'])
_, X_val_temp, y_val_temp = get_xy(val, 'bike_count', ['temp'])
_, X_test_temp, y_test_temp = get_xy(test, 'bike_count', ['temp'])

temp_regresser = LinearRegression()
temp_regresser.fit(X_train_temp, y_train_temp)

print(temp_regresser.coef_, temp_regresser.intercept_)

"""R^2 Score"""

print(temp_regresser.score(X_train_temp, y_train_temp))
print(temp_regresser.score(X_val_temp, y_val_temp))

plt.scatter(X_train_temp, y_train_temp, label='Data', color='blue')
x = tf.linspace(-20, 40, 100)
plt.plot(x, temp_regresser.predict(x.numpy().reshape(-1, 1)), label='Fit', color='red', linewidth=3)
plt.legend()
plt.title("Bikes vs Temperature")
plt.xlabel("Temperature")
plt.ylabel("Bikes")
plt.show()

"""##Multiple Linear Regression"""

_, X_train, y_train = get_xy(train, 'bike_count', df.columns[1:])
_, X_val, y_val = get_xy(val, 'bike_count', df.columns[1:])
_, X_test, y_test = get_xy(test, 'bike_count', df.columns[1:])

all_reg = LinearRegression()
all_reg.fit(X_train, y_train)

all_reg.score(X_train, y_train)

"""Regression with Neural Net"""

temp_normalizer = tf.keras.layers.Normalization(input_shape = (1,), axis=None)
temp_normalizer.adapt(X_train_temp.reshape(-1))

temp_nn_model = tf.keras.Sequential([
    temp_normalizer,
    tf.keras.layers.Dense(units=1)
])

temp_nn_model.compile(optimizer=tf.optimizers.Adam(learning_rate=0.1),
                      loss=tf.keras.losses.MeanSquaredError())

history = temp_nn_model.fit(
    X_train_temp, y_train_temp, epochs=1000,
    verbose=0,
    validation_data = (X_val_temp, y_val_temp))

def plot_loss(history):
  plt.plot(history.history['loss'], label='loss')
  plt.plot(history.history['val_loss'], label='val_loss')
  plt.xlabel('Epoch')
  plt.ylabel('MSE')
  plt.legend()
  plt.grid(True)
  plt.show()

plot_loss(history)

print('Training Loss History:')
print(history.history['loss'])
print('\nValidation Loss History:')
print(history.history['val_loss'])

normalizer = tf.keras.layers.Normalization(axis=-1)
normalizer.adapt(X_train)

nn_model = tf.keras.Sequential([
    normalizer,
    tf.keras.layers.Dense(units=1)
])

nn_model.compile(optimizer=tf.optimizers.Adam(learning_rate=0.1),
                      loss=tf.keras.losses.MeanSquaredError())

history = nn_model.fit(
    X_train, y_train, epochs=1000,
    verbose=0,
    validation_data = (X_val, y_val))

plot_loss(history)

"""#Neural Net"""

temp_normalizer = tf.keras.layers.Normalization(input_shape = (1,), axis=None)
temp_normalizer.adapt(X_train_temp.reshape(-1))

_nn_model = tf.keras.Sequential([
    temp_normalizer,
    tf.keras.layers.Dense(32, activation='relu'),
    tf.keras.layers.Dense(32, activation='relu'),
    tf.keras.layers.Dense(1, activation='relu')
])
_nn_model.compile(optimizer=tf.optimizers.Adam(learning_rate=0.001),
                  loss=tf.keras.losses.MeanSquaredError())
history = _nn_model.fit(
    X_train_temp, y_train_temp, epochs=1000,
    verbose=0,
    validation_data = (X_val_temp, y_val_temp))

plot_loss(history)

plt.scatter(X_train_temp, y_train_temp, label='Data', color='blue')
x = tf.linspace(-20, 40, 100)
plt.plot(x, _nn_model.predict(x.numpy().reshape(-1, 1)), label='Fit', color='red', linewidth=3)
plt.legend()
plt.title("Bikes vs Temperature")
plt.xlabel("Temperature")
plt.ylabel("Bikes")
plt.show()

y_pred_linear = all_reg.predict(X_test)
y_pred_nn = nn_model.predict(X_test)

def MSE(y_pred, y_real):
  return (np.square(y_pred - y_real)).mean()

print(MSE(y_pred_linear, y_test))

print(MSE(y_pred_nn, y_test))

