# -*- coding: utf-8 -*-
"""ml_revision.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Kst4kctU8QXaQPkyWDK1p8Y26hKjMiLg
"""

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from sklearn.preprocessing import StandardScaler
from imblearn.over_sampling import RandomOverSampler

cols = ['fLength', 'fWidth', 'fSize', 'fConc', 'fConc1', 'fAsym', 'fM3Long', 'fM3Trans', 'fAlpha', 'fDist', 'class']
df = pd.read_csv('magic04.data', names=cols)
df.head()

print("Unique values in 'class' before conversion:")
print(df['class'].unique())

"""The output above will show the exact values. If there are extra spaces, for example, ` 'g'` instead of ` 'g'`, the direct comparison `df['class'] == "g"` will evaluate to `False`. To fix this, we can strip any whitespace before comparison."""

df['class'] = (df['class'] == "g").astype(int)
df.head()

for label in cols[:-1]:
  plt.hist(df[df["class"] == 1][label], color='blue', alpha=0.7, density=True, label='gamma')
  plt.hist(df[df["class"] == 0][label], color='red', alpha=0.7, density=True, label='hadron')
  plt.title(f"Distribution of {label}")
  plt.ylabel("Probability")
  plt.xlabel(label)
  plt.legend()
  plt.show()

"""##Train, Validation and Test datasets"""

train, valid, test = np.split(df.sample(frac=1), [int(0.6*len(df)), int(0.8*len(df))])

def scale_dataset(dataframe, oversample=False):
  x = dataframe[dataframe.columns[:-1]].values
  y = dataframe[dataframe.columns[-1]].values

  scaler = StandardScaler()
  x = scaler.fit_transform(x)

  if oversample:
    ros = RandomOverSampler()
    x, y = ros.fit_resample(x, y)

  data = np.hstack((x, np.reshape(y, (-1, 1))))

  return data, x, y

print(len(train[train['class'] == 1]))
print(len(train[train['class'] == 0]))

train, X_train, y_train = scale_dataset(train, oversample=True)
valid, X_valid, y_valid = scale_dataset(valid, oversample=False)
test, X_test, y_test = scale_dataset(test, oversample=False)

"""## kNN"""

from sklearn.neighbors import KNeighborsClassifier
from sklearn.metrics import classification_report

knn_model = KNeighborsClassifier(n_neighbors=4)
knn_model.fit(X_train, y_train)

y_pred = knn_model.predict(X_test)

print(classification_report(y_test, y_pred))

"""##Naive Bayes"""

from sklearn.naive_bayes import GaussianNB

nb_model = GaussianNB()
nb_model = nb_model.fit(X_train, y_train)

y_pred = nb_model.predict(X_test)
print(classification_report(y_test, y_pred))

"""##Logistic Regression"""

from sklearn.linear_model import LogisticRegression

lg_model = LogisticRegression()
lg_model = lg_model.fit(X_train, y_train)

y_pred = lg_model.predict(X_test)
print(classification_report(y_test, y_pred))

"""##SVM"""

from sklearn.svm import SVC

svm_model = SVC()
svm_model.fit(X_train, y_train)
# This cell's code is correct, but there's a related issue in the neural network training loop (cell KtmuuvTQF5wc).

y_pred = svm_model.predict(X_test)
print(classification_report(y_test, y_pred))

"""##Neural Network for classification"""

import tensorflow as tf

nn_model = tf.keras.Sequential([
  tf.keras.layers.Dense(32, activation='relu', input_shape=(10,)),
  tf.keras.layers.Dense(32, activation='relu'),
  tf.keras.layers.Dense(1, activation='sigmoid')
])

nn_model.compile(optimizer=tf.keras.optimizers.Adam(learning_rate=0.001), loss='binary_crossentropy', metrics=['accuracy'])

def plot_loss(history):
  plt.plot(history.history['loss'], label='loss')
  plt.plot(history.history['val_loss'], label='val_loss')
  plt.xlabel('Epoch')
  plt.ylabel('Binary crossentropy')
  plt.legend()
  plt.grid(True)
  plt.show()

def plot_accuracy(history):
  plt.plot(history.history['accuracy'], label='accuracy')
  plt.plot(history.history['val_accuracy'], label='val_accuracy')
  plt.xlabel('Epoch')
  plt.ylabel('Accuracy')
  plt.legend()
  plt.grid(True)
  plt.show()

history = nn_model.fit(
    X_train, y_train,
  validation_split=0.2,
  batch_size=32,
  epochs=100,
  verbose=0
)

plot_loss(history)
plot_accuracy(history)

def train_model(X_train, y_train, num_nodes, dropout_prob, lr, batch_size, epochs):
  nn_model = tf.keras.Sequential([
    tf.keras.layers.Dense(num_nodes, activation='relu', input_shape=(10,)),
    tf.keras.layers.Dropout(dropout_prob),
    tf.keras.layers.Dense(num_nodes, activation='relu'),
    tf.keras.layers.Dropout(dropout_prob),
    tf.keras.layers.Dense(1, activation='sigmoid')
  ])

  nn_model.compile(optimizer=tf.keras.optimizers.Adam(learning_rate=lr), loss='binary_crossentropy', metrics=['accuracy'])

  history = nn_model.fit(
    X_train, y_train,
    validation_split=0.2,
    batch_size=batch_size,
    epochs=epochs,
    verbose=0
  )

  return nn_model, history

least_validation_loss = float('inf')
best_model = None
epochs = 100
for num_nodes in [16, 32, 64]:
  for dropout_prob in [0, 0.2]:
    for lr in [0.01, 0.005, 0.001]:
      for batch_size in [32, 64, 128]:
        print(f"Training with {num_nodes} nodes, dropout {dropout_prob}, lr {lr}, batch size {batch_size}")
        model, history = train_model(X_train, y_train, num_nodes, dropout_prob, lr, batch_size, epochs)
        plot_loss(history)
        plot_accuracy(history)
        val_loss_value = model.evaluate(X_valid, y_valid, verbose=0)[0]

        if val_loss_value < least_validation_loss:
          least_validation_loss = val_loss_value
          best_model = model

y_pred = best_model.predict(X_test)
y_pred = (y_pred > 0.5).astype(int).reshape(-1,)
print(classification_report(y_test, y_pred))