# -*- coding: utf-8 -*-
"""unsupervised_revision.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1gBGiSnt4MxCkAvrPdOcfryNNpmFEbG8U
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

cols = ["area", "perimeter", "compactness", "length", "width", "assymetry", "groove", "class"]
df = pd.read_csv("seeds_dataset.txt", names=cols, sep="\s+")
df.head()

for i in range(len(cols) - 1):
  for j in range(i + 1, len(cols) - 1):
    x_label = cols[i]
    y_label = cols[j]
    sns.scatterplot(x=x_label, y=y_label, data=df, hue="class")
    plt.show()

"""##Clustering"""

from sklearn.cluster import KMeans

x = "compactness"
y = "assymetry"

X = df[[x, y]].values

kmeans = KMeans(n_clusters=3).fit(X)

clusters = kmeans.labels_

clusters

df['class'].values

cluster_df = pd.DataFrame(np.hstack((X, clusters.reshape(-1, 1))), columns=['x', 'y', 'class'])

sns.scatterplot(x='x', y='y', data=cluster_df, hue='class')
plt.show()

"""#Higher Dimensions"""

X = df[cols[:-1]].values
kmeans = KMeans(n_clusters=3).fit(X)
cluster_df = pd.DataFrame(np.hstack((X, clusters.reshape(-1, 1))), columns=df.columns)

sns.scatterplot(x=x, y=y, data=cluster_df, hue='class')
plt.show()

sns.scatterplot(x=x, y=y, data=df, hue='class')
plt.show()

"""##PCA"""

from sklearn.decomposition import PCA

pca = PCA(n_components=2)
X_pca = pca.fit_transform(X)

plt.scatter(X_pca[:, 0], X_pca[:, 1])
plt.show()

kmeans_pca_df = pd.DataFrame(np.hstack((X_pca, kmeans.labels_.reshape(-1, 1))), columns=['pca1', 'pca2', 'class'])

truth_pca_df = pd.DataFrame(np.hstack((X_pca, df['class'].values.reshape(-1, 1))), columns=['pca1', 'pca2', 'class'])

sns.scatterplot(x='pca1', y='pca2', data=kmeans_pca_df, hue='class')
plt.show()

sns.scatterplot(x='pca1', y='pca2', data=truth_pca_df, hue='class')
plt.show()

